### ISSUE TITLE
iButton parser

### ISSUE THREAD

**Issue by vtumino** [TimeLord2010/TeltonikaParser#10]
I can't understand how to parse iButton ID (AVL_ID 78).
For example with button id E50000014B9E8B01 the parser return 314988062570029654899 (using function extractValue). Any idea ?

**Comment by TimeLord2010** [comment]
are you familiar with zod?
I use this schema to parse the value:
```javascript

const iButtonStringSchema = z.union([
    string().length(15, {
        message: 'Parsed iButton must be 15 characters long'
    }).regex(/^[0-9A-F]+$/i),
    string().length(18, {
        message: 'Raw iButton must be 18 characters long'
    }).regex(/^[0-9]+$/).transform(x => {
        const a = BigInt(x)
        return a.toString(16)
    }),
])

const iButtonValueSchema = iButtonStringSchema.or(z.literal(0).or(z.literal('0')).transform(x => {
    const value = ''.padEnd(15, '0');
    return iButtonStringSchema.parse(value)
}))
```

However, the value you gave does'nt seem to be valid. are you sure they are correct?

**Comment by vtumino** [comment]
Thanks @TimeLord2010, I used zod as you suggest and everything works fine.

I actually also had to read the AVL without using the extractValue function and had to pad the result:

`var result =  iButtonValueSchema.parse(rawValue).padStart(16,'0');`

**Comment by TimeLord2010** [comment]
Happy to help!
