### ISSUE TITLE
Item quantity did not match

### ISSUE THREAD

**Issue by vtumino** [TimeLord2010/TeltonikaParser#11]
In some cases I receive an _Item quantity did not match error_ after a 

` new ProtocolParser(rawData);`

for example with this datas:

`00000000000003138e040000018d7f6cfaa80008baad0415ead570004a01530f001c00000025000e00ef0100150500c80000450100b30000020000b40000511f00520e005900006f0000720000980000eb00000b0042395a00430fb30011fff50012ff76005400e6005504aa005a0000006e000000700000007303bc00970000000c00f1000056c200c7000088b80010008467d101c1000f4fc4005300000000005706b164e8006400000000006600000000006700000000006900000000006b0000000000bb00000000000000000000018d7f6d0e300008baa23615eae070004801220f001f00000025000e00ef0100150500c80000450100b30000020000b40000512500521e005900006f0000720000980000eb00000b0042395a00430fb30011ff5600120068005400e60055047f005a0000006e000000700000007303b600970000000c00f1000056c200c7000088b80010008467d101c1000f4fc9005300000000005706b164e8006400000000006600000000006700000000006900000000006b0000000000bb00000000000000000000018d7f6decd80008b8e60115eb07700043010c0f004300000025000e00ef0100150400c80000450100b30000020000b400005142005200005900006f0000720000980000eb00000b0042396e00430fb30011004b00120030005400e600550444005a0000006e000000700000007303b900970000000c00f1000056c200c700008ca0001000846bb901c1000f5002005300000000005706b168d0006400000000006600000000006700000000006900000000006b0000000000bb00000000000000000000018d7f6ebfc80008b72f5515eb17410041011c0e004600000025000e00ef0100150400c80000450100b30000020000b400005141005200005900006f0000720000980000eb00000b0042396400430fb30011ffea00120081005400e60055039c005a0000006e000000700000007303ac00970000000c00f1000056c200c700009088001000846fa101c1000f5039005300000000005706b16cb8006400000000006600000000006700000000006900000000006b0000000000bb000000000000000004000027f`

What does it mean ?

**Comment by TimeLord2010** [comment]
This is not common. It means the packet is invalid. But since it has a valid CRC, then, it means the device produced the invalid data from the start.

You should not consider such packets because they could contain nonsense data.

Maybe the device is broken, but if it rare then is ok. Also reseting the device usually helps.
