### ISSUE TITLE
Please Give Me A Example How To Send Command Teltonika device

### ISSUE THREAD

**Issue by cc-nabeel** [TimeLord2010/TeltonikaParser#2]

**Comment by TimeLord2010** [comment]
TeltonikaParser/Scripts/GPRS Parser/GPRSparser.ts -> gerateCodec12

use like below:
`let commandPacket = gerateCodec12('getinfo')`

Note that this is not importable yet since I still have to make some tests. You'll have to copy and paste the code for now.

As for how to send it, I think you can use a Socket for that:
```
function gerateByteArray (packet) {               
    let r = new Uint8Array(packet.length / 2)
    // Untested. You may need to insert every byte in ascending order instead of descending.
    for (let i = 0, k = packet.length - 2; i < packet.length; i++, k = k - 2) {
      r[i] = parseInt(packet.substr(k, 2), 16)
    }
    return r
}
let response = gerateByteArray('your command in hex string format')
client.write(response)
```

**Comment by cc-nabeel** [comment]
bro thanks 

// Command Send
forExample This Command :flush 353976012555151,banga,,,212.47.99.62,12050,0
then i was convert command in hexa  : let cmd 
 = '666c757368203335333937363031323535353135312c62616e67612c2c2c3231322e34372e39392e36322c31323035302c30'
let response = gerateByteArray(cmd)
client.write(response)
i am doing right

if your answer is yes how i receive command response 
can  we receive command response in this data
  c.on("data", (data) => {

})
if your answer is yes but how i detect this is command response
and another question is how i get device serial number 
                                                                                 Thanks TimeLord2010
                                                                     TimeLord2010 please give me answer i want answer please help bro

**Comment by TimeLord2010** [comment]
> forExample This Command :flush 353976012555151,banga,,,212.47.99.62,12050,0
> then i was convert command in hexa : 
> let cmd = '666c757368203335333937363031323535353135312c62616e67612c2c2c3231322e34372e39392e36322c31323035302c30'
> let response = gerateByteArray(cmd)
> client.write(response)
> i am doing right

Your command seems weird. But as long as this is a valid command, you are doing it right.

> can we receive command response in this data
> c.on("data", (data) => {
> 
> })

yes.

> if your answer is yes but how i detect this is command response
> and another question is how i get device serial number

The issue with these is that the device uses the same connection type to send its IMEI, commands, response to the commands, and data packets.

As stated in the read.me, I checked if the data is an imei using a similar code:

```typescript
function processPacket (packet) {
    if (packet.length == 34) {
        return {
            imei: parseIMEI(packet)
        }
    } else {
        return { 
            dataPacket: new ProtocolParser(packet)
        }
    }
}
```
_This code was made in a TCP connection environment_

When receiving the device response for the command, check for the codec 12 ('C' in hex).

Note: Serial Number and IMEI are two different things, at least in some devices. For example, the model TRB245, has IMEI and Serial Number.

In case you are looking for the actual serial number, This is no way to get it using the parser as this data is not present in the packet, useless explicitly requested by a command, if such exists.
