### ISSUE TITLE
Lat Long error

### ISSUE THREAD

**Issue by estrickitrakes** [TimeLord2010/TeltonikaParser#3]
I tried it out of curiosity and it gave me an error in the latitude, I could fix this by making a small change, it had a function that I use for some time.

`function getGPSdata(gum) {
	var bon = parseInt(gum, 10),
		largo = bon.length;
	largo = +largo || 32;
	if (largo > 32) throw new RangeError('uintToInt only supports ints up to 32 bits');
	gum <<= 32 - largo;
	gum >>= 32 - largo;
	gum = gum / 10000000;
	return gum;
}`

Saludos!

**Comment by TimeLord2010** [comment]
Can you post an reproducible example?

**Comment by estrickitrakes** [comment]
Try this:
`00000000000000628e010000017a52dc444800c42dd67b0c443bce000000000000000000000c000500f00100150200c800004502007143000500b5000000b600000018000000430f1d00440000000100f1000518c400000001037b000c44444245353930444442353801000001f2`

The answer for the Longitude is -329.1338363 :

` AVL_Data {`
`    Timestamp: 2021-06-28T13:43:25.000Z,`
`    Priority: 0,`
`    GPSelement: GPSelement {`
`      Longitude: -329.1338363,`
`      Latitude: 20.579835,`
`      Altitude: 0,`
`      Angle: 0,`
`      Satellites: 0,`
`      Speed: 0`
`    },`
`    IOelement: IOelement { EventID: 0, ElementCount: 12, Elements: [Object] }`
`  }`

After changing the "getGPSdata" function to:

`function getGPSdata(gum) {`
` var bon = parseInt(gum, 10), `
` largo = bon.length; `
` largo = +largo || 32;`
` if (largo > 32) throw new RangeError('uintToInt only supports ints up to 32 bits');`
` gum <<= 32 - largo; gum >>= 32 - largo;` 
`gum = gum / 10000000; `
`return gum; `
`}`

the Longitude answer is correct 

` AVL_Data {`
`    Timestamp: 2021-06-28T13:43:25.000Z,`
`    Priority: 0,`
`    GPSelement: GPSelement {`
`      Longitude: -100.3628933,`
`      Latitude: 20.579835,`
`      Altitude: 0,`
`      Angle: 0,`
`      Satellites: 0,`
`      Speed: 0`
`    },`
`    IOelement: IOelement { EventID: 0, ElementCount: 12, Elements: [Object] }`
`  }`

**Comment by TimeLord2010** [comment]
Sorry for the long wait. I'll be testing this today. If indeed true, I'll fix it in the next release.

**Comment by TimeLord2010** [comment]
Your functions passes the tests, but I believe you've made some miscalculation along the way. Variable `largo` will always have the value of 32. Therefore, the final implementation can be:
```typescript
export function getGPSdata(gum: number) {
    gum <<= 32; 
    gum >>= 32;
    gum = gum / 10000000;
    return gum;
}

```
