### ISSUE TITLE
ASCII data

### ISSUE THREAD

**Issue by inteloid** [TimeLord2010/TeltonikaParser#4]
Hi,
Seems like the parser doesn't parse ASCII messages, or there's an issue on my code supplying the parser with data.

Please tell me the status with ASCII messages, maybe I can contribute if that part is missing.

Thanks for the work you're doing!

**Comment by TimeLord2010** [comment]
I couldn't check properly GPRS protocols when I was working with Teltonika devices. You can make a pull request if you have a working code. But please submit a sample packet so I can set up unit tests.
