### ISSUE TITLE
Preamble should be 0

### ISSUE THREAD

**Issue by zhaxal** [TimeLord2010/TeltonikaParser#5]
I am getting "Preamble should be 0" when parsing this packet:

`const packet = "16030100fc010000f80303c5b7b0dd4f43ec2edd6d126ca9a23374e586e9acefa37bc0312088900fa7503a00008cc030c02cc032c02ec02fc02bc031c02d00a500a300a1009f00a400a200a0009ec028c024c014c00ac02ac026c00fc005006b006a006900680039003800370036c027c023c013c009c029c025c00ec00400670040003f003e003300320031003000880087008600850045004400430042009d009c003d0035003c002f00840041c011c007c00cc002000500ff01000043000b000403000102000a000a0008001700190018001600230000000d0020001e060106020603050105020503040104020403030103020303020102020203000f000101"`

**Comment by TimeLord2010** [comment]
How did you get the packet? It doeen't seem to be valid. Make sure the device gerates packet using TCP comnection instead of UDP.

Valid packets start with 0000.
